name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.1-focal
      env:
        ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Start the shopping store application"
          chmod +x ./shopping-store-linux-arm64
          ./shopping-store-linux-arm64 &
          echo "Wait for backend to be ready..."
          for i in {1..20}; do
            nc -z localhost 2221 && echo "Backend is up!" && break
            echo "Waiting for backend... ($i)"
            sleep 2
          done
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run test:ci
